version: '3.8'

services:
  backend:
    container_name: customers-api-backend
    build: .
    env_file: ./.env
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - nbridge
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

  db:
    container_name: customers-db
    image: postgres:14.6-alpine
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nbridge
    expose:
      - 5432
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

volumes:
  db-data:
    driver: local

networks:
  nbridge:
    driver: bridge
